// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"sjjlas7sz8","name":"AnalyzeMission","description":"Used to validate mission way points against images taken by the Drone","endpoint":"https://sjjlas7sz8.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/mission","/mission/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:7d6c20aa-e92f-488a-9645-eeacc727505e',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'dronemissionanalyzer-hosting-mobilehub-1163272740',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd33zx1g83jj36j.cloudfront.net',
    'aws_mobile_analytics_app_id': 'd5f752f9041d4491b4a70142e822f68c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e361cf89-ca65-4924-96cf-e00dd0d086b2',
    'aws_project_name': 'DroneMissionAnalyzer',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'dronemissionanalyzer-deployments-mobilehub-1163272740',
    'aws_resource_name_prefix': 'dronemissionanalyzer-mobilehub-1163272740',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'dronemissionanalyzer-userfiles-mobilehub-1163272740',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_c3yYHzW1q',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '6u8b509imheio5hsbsirugtqvc',
    'aws_user_settings': 'enable',
}

export default awsmobile;
